### ISSUE TITLE
The component of stackstrom cannot connect to mongodb

### ISSUE THREAD

**Issue by xuanyuanaosheng** [StackStorm/stackstorm-ha#210]
The components of stackstrom can not connect to mongodb. The install was failed.

kubectl get pods 
```
NAME                                                 READY   STATUS             RESTARTS   AGE
stackstorm-ha-job-st2-apikey-load-ps8rj              0/1     Init:1/3           0          18h
stackstorm-ha-mongodb-0                              1/1     Running            0          80m
stackstorm-ha-mongodb-1                              1/1     Running            0          81m
stackstorm-ha-mongodb-2                              1/1     Running            0          81m
stackstorm-ha-rabbitmq-0                             1/1     Running            1          18h
stackstorm-ha-rabbitmq-1                             1/1     Running            1          18h
stackstorm-ha-rabbitmq-2                             1/1     Running            1          18h
stackstorm-ha-redis-node-0                           2/2     Running            0          18h
stackstorm-ha-redis-node-1                           2/2     Running            0          18h
stackstorm-ha-redis-node-2                           2/2     Running            0          18h
stackstorm-ha-st2actionrunner-56d6c5c79-k4dcm        0/1     CrashLoopBackOff   216        18h
stackstorm-ha-st2actionrunner-56d6c5c79-rj6qn        0/1     CrashLoopBackOff   216        18h
stackstorm-ha-st2api-9bcb84857-6kpsw                 0/1     CrashLoopBackOff   217        18h
stackstorm-ha-st2auth-7f99b9b966-4xxps               0/1     CrashLoopBackOff   214        18h
stackstorm-ha-st2client-744f4565cb-2sxgs             1/1     Running            0          18h
stackstorm-ha-st2garbagecollector-8595d597b8-bwtx9   0/1     CrashLoopBackOff   216        18h
stackstorm-ha-st2notifier-69c4688cfc-zbnv8           0/1     CrashLoopBackOff   216        18h
stackstorm-ha-st2rulesengine-86b77bd478-rbs76        0/1     CrashLoopBackOff   216        18h
stackstorm-ha-st2scheduler-76bcf589c5-n2d42          0/1     CrashLoopBackOff   217        18h
stackstorm-ha-st2sensorcontainer-f46879bc8-xvlwz     0/1     CrashLoopBackOff   17         65m
stackstorm-ha-st2stream-797d77cc46-g6wql             0/1     CrashLoopBackOff   217        18h
stackstorm-ha-st2timersengine-676c97f9c5-6hkzz       0/1     CrashLoopBackOff   216        18h
stackstorm-ha-st2web-6f5fd9b746-bmg54                1/1     Running            0          18h
stackstorm-ha-st2workflowengine-5d6f57b7dc-8lzbk     0/1     CrashLoopBackOff   216        18h
```

kubectl get service
```
NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                 AGE
stackstorm-ha-mongodb-headless    ClusterIP   None            <none>        27017/TCP                               18h
stackstorm-ha-rabbitmq            ClusterIP   10.62.123.97    <none>        5672/TCP,4369/TCP,25672/TCP,15672/TCP   18h
stackstorm-ha-rabbitmq-headless   ClusterIP   None            <none>        4369/TCP,5672/TCP,25672/TCP,15672/TCP   18h
stackstorm-ha-redis               ClusterIP   10.62.252.219   <none>        6379/TCP,26379/TCP                      18h
stackstorm-ha-redis-headless      ClusterIP   None            <none>        6379/TCP,26379/TCP                      18h
stackstorm-ha-st2api              ClusterIP   10.62.139.83    <none>        9101/TCP                                18h
stackstorm-ha-st2auth             ClusterIP   10.62.228.20    <none>        9100/TCP                                18h
stackstorm-ha-st2stream           ClusterIP   10.62.199.230   <none>        9102/TCP                                18h
stackstorm-ha-st2web              NodePort    10.62.191.23    <none>        80:36652/TCP                            18h
```

The configmap of stackstorm-ha-st2-config
```
[auth]
api_url = http://stackstorm-ha-st2api:9101/
[coordination]
url = redis://stackstorm-ha-redis-node-0.stackstorm-ha-redis-headless:26379?sentinel=mymaster&sentinel_fallback=stackstorm-ha-redis-node-1.stackstorm-ha-redis-headless:26379&sentinel_fallback=stackstorm-ha-redis-node-2.stackstorm-ha-redis-headless:26379
[messaging]
url = amqp://admin:9jS+w1u07NbHtZke1m+jW4Cj@stackstorm-ha-rabbitmq:5672/
[database]
host = mongodb://stackstorm-ha-mongodb-0.stackstorm-ha-mongodb-headless,stackstorm-ha-mongodb-1.stackstorm-ha-mongodb-headless,stackstorm-ha-mongodb-2.stackstorm-ha-mongodb-headless/st2?authSource=st2&replicaSet=rs0
username = st2-admin
password = XeL5Rxwj7F0Wt43tFZVTN7H8Sg5XDHmK
db_name = st2
port = 27017

```
The mongodb status in containter:

![image](https://user-images.githubusercontent.com/4197714/123372748-b7d6bd80-d5b6-11eb-9f3a-3fbc4ae2c61c.png)

From the above the configs about mongodb looks OK.

But the  all components that can not connect the mongodb error log is 
```
2021-06-25 04:48:21,971 INFO [-] Using fs encoding: utf-8, default encoding: utf-8, locale: en_US.UTF-8, LANG env variable: en_US.UTF-8, PYTHONIOENCODING env variable: notset
2021-06-25 04:48:21,971 INFO [-] Using config files: /etc/st2/st2.conf,/etc/st2/st2.docker.conf,/etc/st2/st2.user.conf
2021-06-25 04:48:21,972 INFO [-] Using logging config: /etc/st2/logging.api.gunicorn.conf
2021-06-25 04:48:21,972 INFO [-] Using coordination driver: redis
2021-06-25 04:48:21,972 INFO [-] Using metrics driver: noop
2021-06-25 04:48:21,989 INFO [-] Connecting to database "st2" @ "stackstorm-ha-mongodb-0.stackstorm-ha-mongodb-headless:27017,stackstorm-ha-mongodb-1.stackstorm-ha-mongodb-headless:27017,stackstorm-ha-mongodb-2.stackstorm-ha-mongodb-headless:27017 (replica set)" as user "st2-admin".
2021-06-25 04:48:25,015 ERROR [-] Failed to connect to database "st2" @ "stackstorm-ha-mongodb-0.stackstorm-ha-mongodb-headless:27017,stackstorm-ha-mongodb-1.stackstorm-ha-mongodb-headless:27017,stackstorm-ha-mongodb-2.stackstorm-ha-mongodb-headless:27017 (replica set)" as user "st2-admin": No replica set members match selector "Primary()", Timeout: 3.0s, Topology Description: <TopologyDescription id: 60d560152e2ac2a2fdf8e96c, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('stackstorm-ha-mongodb-0.stackstorm-ha-mongodb-headless', 27017) server_type: RSGhost, rtt: 0.0015505916917324068>, <ServerDescription ('stackstorm-ha-mongodb-1.stackstorm-ha-mongodb-headless', 27017) server_type: RSGhost, rtt: 0.0009245870429873468>, <ServerDescription ('stackstorm-ha-mongodb-2.stackstorm-ha-mongodb-headless', 27017) server_type: RSGhost, rtt: 0.0008347049045562745>]>
2021-06-25 04:48:25,015 ERROR [-] (PID=1) ST2 API quit due to exception.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2api/cmd/api.py", line 94, in main
    _setup()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2api/cmd/api.py", line 65, in _setup
    capabilities=capabilities,
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/service_setup.py", line 244, in setup
    db_setup()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/database_setup.py", line 55, in db_setup
    connection = db_init.db_setup_with_retry(**db_cfg)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/persistence/db_init.py", line 93, in db_setup_with_retry
    ssl_match_hostname=ssl_match_hostname,
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/persistence/db_init.py", line 58, in db_func_with_retry
    return retrying_obj.call(db_func, *args, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/six.py", line 696, in reraise
    raise value
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/models/db/__init__.py", line 250, in db_setup
    ssl_match_hostname=ssl_match_hostname,
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/models/db/__init__.py", line 212, in _db_connect
    raise e
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/models/db/__init__.py", line 203, in _db_connect
    connection.admin.command("ismaster")
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/pymongo/database.py", line 737, in command
    read_preference, session) as (sock_info, slave_ok):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1325, in _socket_for_reads
    server = self._select_server(read_preference, session)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1278, in _select_server
    server = topology.select_server(server_selector)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/pymongo/topology.py", line 243, in select_server
    address))
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/pymongo/topology.py", line 200, in select_servers
    selector, server_timeout, address)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/pymongo/topology.py", line 217, in _select_servers_loop
    (self._error_message(selector), timeout, self.description))
pymongo.errors.ServerSelectionTimeoutError: No replica set members match selector "Primary()", Timeout: 3.0s, Topology Description: <TopologyDescription id: 60d560152e2ac2a2fdf8e96c, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('stackstorm-ha-mongodb-0.stackstorm-ha-mongodb-headless', 27017) server_type: RSGhost, rtt: 0.0015505916917324068>, <ServerDescription ('stackstorm-ha-mongodb-1.stackstorm-ha-mongodb-headless', 27017) server_type: RSGhost, rtt: 0.0009245870429873468>, <ServerDescription ('stackstorm-ha-mongodb-2.stackstorm-ha-mongodb-headless', 27017) server_type: RSGhost, rtt: 0.0008347049045562745>]>
```

The question:
1.  How to continue troubleshooting?
2. How to fix this?  

If need more info, please add a comment.

The wait-for-db logs
![image](https://user-images.githubusercontent.com/4197714/123373310-c4a7e100-d5b7-11eb-8a65-f8c84670c75f.png)

The mongodb logs is 
[stackstorm_stackstorm-ha-mongodb-0_mongodb.log](https://github.com/StackStorm/stackstorm-ha/files/6713740/stackstorm_stackstorm-ha-mongodb-0_mongodb.log)

My k8s cluster CLUSTER_DNS_DOMAIN="k8s.sre", not the "cluster.local"

**Comment by arms11** [comment]
Hi, what is the chart version?
Also, when you describe mongodb headless service, do you see all 3 endpoints?

**Comment by xuanyuanaosheng** [comment]
@arms11  

The chart version is :
![image](https://user-images.githubusercontent.com/4197714/123506065-e034e980-d694-11eb-9470-88fed0089b98.png)

The kubectl get endpoints
```
NAME                              ENDPOINTS                                                        AGE
stackstorm-ha-mongodb-headless    10.0.6.128:27017,10.0.7.131:27017,10.0.7.230:27017               45h
stackstorm-ha-rabbitmq            10.0.6.188:5672,10.0.6.46:5672,10.0.6.64:5672 + 9 more...        45h
stackstorm-ha-rabbitmq-headless   10.0.6.188:5672,10.0.6.46:5672,10.0.6.64:5672 + 9 more...        45h
stackstorm-ha-redis               10.0.6.228:26379,10.0.7.195:26379,10.0.7.243:26379 + 3 more...   45h
stackstorm-ha-redis-headless      10.0.6.228:26379,10.0.7.195:26379,10.0.7.243:26379 + 3 more...   45h
stackstorm-ha-st2api                                                                               45h
stackstorm-ha-st2auth                                                                              45h
stackstorm-ha-st2stream                                                                            45h
stackstorm-ha-st2web              10.0.6.150:80                                                    45h
```

**Comment by cognifloyd** [comment]
You might want to double check your networking policies - eg, if you're using something like Calico, the calico policies might be blocking some of the traffic. Other solutions should have something similar.

**Comment by xuanyuanaosheng** [comment]
@cognifloyd  Ok, I will do more checking.

**Comment by cognifloyd** [comment]
@xuanyuanaosheng Were you able to resolve the network policies / mongodb connectivity issues?

**Comment by cognifloyd** [comment]
I'm going to close this. Feel free to reopen if this is still an issue for you.

**Comment by usulkies** [comment]
@xuanyuanaosheng I'm experiencing the same issue.
Did you find the solution eventually?

**Comment by chain312** [comment]
> @xuanyuanaosheng I'm experiencing the same issue. Did you find the solution eventually?

@usulkies 

 I'm experiencing the same issue.
Did you find the solution eventually?

**Comment by usulkies** [comment]
@chain312 If I recall correctly, the problem was that the mongodb port wasn't open on the nodes security group. So pods on the same node could connect, but not cross-nodes

**Comment by chain312** [comment]
> @chain312 If I recall correctly, the problem was that the mongodb port wasn't open on the nodes security group. So pods on the same node could connect, but not cross-nodes

I don't have a firewall on my Intranet
