### ISSUE TITLE
st2 pods stuck in loop

### ISSUE THREAD

**Issue by nagrigore** [StackStorm/stackstorm-ha#57]
I'm deploying a stackstorm/stackstorm-ha cluster with helm and since yesterday some of the pods seem to be stuck in a loop.
"Deployment does not have minimum availability". This was previously working without any issues.

We don't have much info on the logs:

 Logs: st2actionrunner
2019-03-21 08:40:38,795 DEBUG [-] Using Python: 2.7.12 (/opt/stackstorm/st2/bin/python)
2019-03-21 08:40:38,796 DEBUG [-] Using config files: /etc/st2/st2.conf,/etc/st2/st2.docker.conf,/etc/st2/st2.user.conf
2019-03-21 08:40:38,796 DEBUG [-] Using logging config: /etc/st2/logging.actionrunner.conf
2019-03-21 08:40:38,802 INFO [-] Connecting to database "st2" @ "aspiring-ferret-mongodb-ha:27017" as user "None".
2019-03-21 08:40:38,830 INFO [-] Successfully connected to database "st2" @ "aspiring-ferret-mongodb-ha:27017" as user "None".
2019-03-21 08:40:39,972 ERROR [-] (PID=1) Worker quit due to exception.
Traceback (most recent call last):
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/actionrunner.py", line 80, in main
_setup()
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/actionrunner.py", line 41, in _setup
register_signal_handlers=True, service_registry=True, capabilities=capabilities)
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 187, in setup
start_heart=True)
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 224, in register_service_in_service_registry
coordinator.create_group(group_id).get()
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/coordination.py", line 476, in create_group
raise tooz.NotImplemented
NotImplemented

=========================
 Logs: st2workflowengine
2019-03-21 08:45:45,742 DEBUG [-] Using Python: 2.7.12 (/opt/stackstorm/st2/bin/python)
2019-03-21 08:45:45,742 DEBUG [-] Using config files: /etc/st2/st2.conf,/etc/st2/st2.docker.conf,/etc/st2/st2.user.conf
2019-03-21 08:45:45,743 DEBUG [-] Using logging config: /etc/st2/logging.workflowengine.conf
2019-03-21 08:45:45,748 INFO [-] Connecting to database "st2" @ "aspiring-ferret-mongodb-ha:27017" as user "None".
2019-03-21 08:45:45,774 INFO [-] Successfully connected to database "st2" @ "aspiring-ferret-mongodb-ha:27017" as user "None".
2019-03-21 08:45:46,633 ERROR [-] Traceback (most recent call last):
2019-03-21 08:45:46,633 ERROR [-] File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/workflow_engine.py", line 94, in main
2019-03-21 08:45:46,633 ERROR [-] setup()
2019-03-21 08:45:46,633 ERROR [-] File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/workflow_engine.py", line 65, in setup
2019-03-21 08:45:46,633 ERROR [-] capabilities=capabilities
2019-03-21 08:45:46,633 ERROR [-] File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 187, in setup
2019-03-21 08:45:46,633 ERROR [-] start_heart=True)
2019-03-21 08:45:46,633 ERROR [-] File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 224, in register_service_in_service_registry
2019-03-21 08:45:46,634 ERROR [-] coordinator.create_group(group_id).get()
2019-03-21 08:45:46,634 ERROR [-] File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/coordination.py", line 476, in create_group
2019-03-21 08:45:46,634 ERROR [-] raise tooz.NotImplemented
2019-03-21 08:45:46,634 ERROR [-] NotImplemented
2019-03-21 08:45:46,634 ERROR [-] (PID=1) Workflow engine quit due to exception.
Traceback (most recent call last):
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/workflow_engine.py", line 94, in main
setup()
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/workflow_engine.py", line 65, in setup
capabilities=capabilities
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 187, in setup
start_heart=True)
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 224, in register_service_in_service_registry
coordinator.create_group(group_id).get()
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/coordination.py", line 476, in create_group
raise tooz.NotImplemented
NotImplemented

=========================

This was installed with command: helm install stackstorm/stackstorm-ha
I've used the same layout to deploy and test few days ago. There's no resources issue.

root@aspiring-ferret-st2client-849f88776f-p4ntd:/opt/stackstorm# st2 --version
st2 3.0dev (0b95862), on Python 2.7.12

**Comment by Kami** [comment]
Let's continue here.

@nagrigore Did you figure it out?

It looks like it's related to recent service registry changes I worked on. Which coordination backed do you have configured in st2.conf?

**Comment by Kami** [comment]
Alright, I found there issue. Workaround is here - https://github.com/StackStorm/st2/pull/4607

Once that PR is merged and new v3.0.0dev packages built, redeploying stackstorm-ha should work.

Thanks again for reporting this issue.

**Comment by armab** [comment]
Thanks @Kami for a quick fix.
We'll check again in a few days when both packages + docker images are available and close the issue.

**Comment by morivall** [comment]
Hello guys,
We're still can not deploy stackstorm-ha from helm.
helm install --name stackstormtest  stackstorm/stackstorm-ha
Here is the log from 1 pod
019-03-21 20:12:48,348 ERROR [-] (PID=1) Worker quit due to exception.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/actionrunner.py", line 80, in main
    _setup()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/actionrunner.py", line 41, in _setup
    register_signal_handlers=True, service_registry=True, capabilities=capabilities)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 187, in setup
    start_heart=True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 224, in register_service_in_service_registry
    coordinator.create_group(group_id).get()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/coordination.py", line 476, in create_group
    raise tooz.NotImplemented
NotImplemented


testcluster-st2actionrunner-77489f94c8-btbt4       0/1     CrashLoopBackOff   5          4m34s
testcluster-st2actionrunner-77489f94c8-rj2v5       0/1     CrashLoopBackOff   5          4m34s
testcluster-st2actionrunner-77489f94c8-tnklq       0/1     CrashLoopBackOff   5          4m34s
testcluster-st2actionrunner-77489f94c8-tr242       0/1     CrashLoopBackOff   5          4m34s
testcluster-st2actionrunner-77489f94c8-vr6r2       0/1     CrashLoopBackOff   5          4m34s
testcluster-st2api-646fc6bfd7-hjjh5                0/1     CrashLoopBackOff   5          4m34s
testcluster-st2api-646fc6bfd7-z2h5w                0/1     CrashLoopBackOff   5          4m34s
testcluster-st2auth-5855d9d5bd-2ktlx               0/1     CrashLoopBackOff   5          4m34s
testcluster-st2auth-5855d9d5bd-sn4mf               0/1     CrashLoopBackOff   5          4m34s
testcluster-st2client-5c55669f6-k7v6j              1/1     Running            0          4m34s
testcluster-st2garbagecollector-8674bc649c-ns8hp   0/1     CrashLoopBackOff   5          4m33s
testcluster-st2notifier-c5b7d59b9-kg8l4            0/1     CrashLoopBackOff   5          4m34s
testcluster-st2notifier-c5b7d59b9-s2pkn            0/1     CrashLoopBackOff   5          4m34s
testcluster-st2rulesengine-fbff5c8dd-bzl5k         0/1     CrashLoopBackOff   5          4m34s
testcluster-st2rulesengine-fbff5c8dd-mkgpg         0/1     CrashLoopBackOff   5          4m34s
testcluster-st2scheduler-77db66bc5b-87crf          0/1     CrashLoopBackOff   5          4m34s
testcluster-st2scheduler-77db66bc5b-9fskj          0/1     CrashLoopBackOff   5          4m34s
testcluster-st2sensorcontainer-65c45f9445-9t9cz    0/1     CrashLoopBackOff   5          4m34s
testcluster-st2stream-599cb6b7b4-4dsmt             0/1     CrashLoopBackOff   5          4m34s
testcluster-st2stream-599cb6b7b4-s7zzn             0/1     CrashLoopBackOff   5          4m34s
testcluster-st2timersengine-6c54464b5f-bns59       0/1     CrashLoopBackOff   5          4m34s
testcluster-st2web-6dd96cf9f7-l5l28                1/1     Running            0          4m33s
testcluster-st2web-6dd96cf9f7-qmhjm                1/1     Running            0          4m33s
testcluster-st2workflowengine-7499f6d446-m9t8r     0/1     CrashLoopBackOff   5          4m33s
testcluster-st2workflowengine-7499f6d446-vmxm2     0/1     CrashLoopBackOff   5          4m33s

**Comment by Kami** [comment]
@nagrigore Just a heads up - PR has been merged and new packages built.

If you redeployed the cluster with the latest version of StackStorm packages, it should work now.

**Comment by armab** [comment]
>  We'll check again in a few days when both packages + docker images are available and close this issue.

Still need some time for packages + Dockerfiles to build based on new code. That will happen likely tomorrow.

**Comment by isilverwood** [comment]
For me personally, the deployments have started to work again. Thanks a bunch @Kami @armab

**Comment by warrenvw** [comment]
Thanks for letting us know that it's working for you. I'll go ahead and close this issue now, please feel free to re-open if necessary.

**Comment by nagrigore** [comment]
Hello,

Seems like the the deploy is working now. 
Thank you!
